// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rdbristichwpgwpnqrbm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJkYnJpc3RpY2h3cGd3cG5xcmJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5MDgxODYsImV4cCI6MjA2NDQ4NDE4Nn0.sxm_muC2od-gRGD21KRkbrA2SswbpEBDwwQse-e-4w0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);